version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/mysite
hooks:
  BeforeInstall:
    - location: kill_server.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: ubuntu